---

- name: create group
  group: name=simple-http-server
  
- name: create user
  user: name=simple-http-server group=simple-http-server createhome=no

- name: create directory for files
  file: path="{{ simple_http_server_home }}" state=directory owner=simple-http-server group=simple-http-server
  notify: restart simple-http-server
  
- name: configure service
  template: src=simple-http-server.service.j2 dest=/lib/systemd/system/simple-http-server.service
  notify: restart simple-http-server

- name: reload systemd
  command: systemctl daemon-reload
  changed_when: false
  
