---
  # need to specify owner/group otherwise ansible creates files as uucp:143
- name: extract
  unarchive: copy=no src="https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip" dest=/usr/local/bin/ owner=root group=root creates=/var/lib/ansible/done/packer_{{ packer_version }}.done

- name: update ansible done files
  file: path=/var/lib/ansible/done/packer_{{ packer_version }}.done state=touch
  changed_when: false
