---
  # need to specify owner/group otherwise ansible creates files as uucp:143
- name: extract maven
  unarchive: copy=no src=http://www.trieuvan.com/apache/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz dest=/opt owner=root group=root

  # buildomatic wants maven under /usr/local
- name: symlink maven home to make buildomatic happy
  file: src=/opt/apache-maven-{{ maven_version }} dest=/usr/local/maven owner=root group=root state=link
  
- name: symlinks maven binary
  file: src=/usr/local/maven/bin/mvn dest=/usr/local/bin/mvn owner=root group=root state=link
  
