---
- name: check if maven is already installed
  stat: path=/var/lib/ansible/done/apache-maven-{{ maven_version }}.done
  register: maven_done_file

  # if stat.isdir is not defined it means the path doesn't exist, so no need to check for stat.islink
- include: install_maven.yml
  when: maven_done_file.stat.isdir is not defined

- name: update ansible done files
  file: path=/var/lib/ansible/done/apache-maven-{{ maven_version }}.done state=touch
  changed_when: false
