---

- name: check if maven is already present
  stat: path=/usr/local/maven
  register: maven_location

  # if stat.isdir is not defined it means the path doesn't exist, so no need to check for stat.islink
- include: install_maven.yml
  when: maven_location.stat.isdir is not defined
