---

  # user/group to run jenkins process
- name: create jenkins group
  group: name=jenkins
  
- name: create jenkins user
  user: name=jenkins group=jenkins groups=shadow,docker

- name: configure git for jenkins user
  template: src=.gitconfig.j2 dest=/home/jenkins/.gitconfig

  # user/group to administer jenkins
- name: create jenkins-admins group
  group: name=jenkins-admins
  
- name: create jenkins-admin user
  user: name=jenkins-admin groups=jenkins-admins createhome=no

