---

- name: set up nexus data directory
  file: path="{{ nexus_data_location }}" state=directory owner=200 recurse=yes
  
- name: setup nexus container
  docker:
    name: nexus
    image: "sonatype/nexus:oss"  
    state: reloaded
    restart_policy: always
    volumes:
      - "{{ nexus_data_location }}:/sonatype-work"
    ports:
      - "18081:8081"
    # https://github.com/ansible/ansible-modules-core/issues/1129
    # https://github.com/ansible/ansible-modules-core/issues/1251
    # https://github.com/ansible/ansible-modules-core/pull/1609
    # https://github.com/ansible/ansible-modules-core/issues/1130
    # have to use net=bridge until the bug is resloved.
    # otherwise the container is always restarted
    net: bridge
