---

- name: copy keystore
  copy: src="{{ jenkins_keystore_file }}" dest="{{ jenkins_home }}/keystore" owner=jenkins group=jenkins
  notify: restart jenkins
  when: jenkins_keystore_file is defined

- name: generate keystore
  command: >
    {{ jenkins_java | dirname }}/keytool -genkeypair -keysize 2048 -keyalg RSA -alias jenkins -keystore keystore -storepass {{ jenkins_keystore_password }} -keypass {{ jenkins_keystore_password }} -dname "CN=none, OU=none, O=none, L=none, ST=none, C=none"
    chdir="{{ jenkins_home }}"
    creates="{{ jenkins_home }}/keystore"
  become_user: jenkins
  notify: restart jenkins
  when: jenkins_keystore_file is not defined
