---

- name: add docker repository to apt
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-vivid main'

- name: add docker key to apt
  apt_key: keyserver=hkp://pgp.mit.edu:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: install
  apt: name=docker-engine update_cache=yes
  notify: restart docker

- name: enable service
  service: name=docker enabled=yes
