---

- name: add docker repository to apt
  apt_repository: repo='deb http://get.docker.com/ubuntu docker main'

- name: add docker key to apt
  apt_key: keyserver=pgp.mit.edu id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: install docker
  apt: name=lxc-docker update_cache=yes
  notify: restart docker

- name: enable service
  service: name=docker enabled=yes
