---

- name: create docker-registry storage directory
  file: path={{ docker_registry_storage_location }} state=directory

- name: install and start docker-registry container
  docker:
    name: registry
    image: "registry:2"
    state: reloaded
    restart_policy: always
    volumes:
      - "{{ docker_registry_storage_location }}:/var/lib/registry"
    ports:
      - "5000:5000"
    # https://github.com/ansible/ansible-modules-core/issues/1129
    # https://github.com/ansible/ansible-modules-core/issues/1251
    # https://github.com/ansible/ansible-modules-core/pull/1609
    # https://github.com/ansible/ansible-modules-core/issues/1130
    # have to use net=bridge until the bug is resloved.
    # otherwise the container is always restarted
    net: bridge

