---

- name: create docker-registry storage directory
  file: path=/var/lib/docker-registry state=directory

- name: install and start docker-registry container
  docker:
    name: registry
    image: "registry:2"
    state: reloaded
    restart_policy: always
    volumes:
      - "/var/lib/docker-registry:/var/lib/registry"
    ports:
      - "5000:5000"
    # https://github.com/ansible/ansible-modules-core/issues/1129
    # https://github.com/ansible/ansible-modules-core/issues/1251
    # https://github.com/ansible/ansible-modules-core/pull/1609
    # https://github.com/ansible/ansible-modules-core/issues/1130
    # have to use net=bridge until the bug is resloved.
    # otherwise the container is always restarted
    net: bridge

