---

- name: install and start docker-registry container
  docker:
    name: docker-registry
    image: "registry:{{ docker_registry_version }}"
    state: running
    volumes:
      - "/tmp/registry"
    ports:
      - "5000:5000"

- name: create service
  template: src=docker-registry.service.j2 dest=/lib/systemd/system/docker-registry.service
  notify: restart docker-registry
  
- name: enable service
  service: name=docker-registry enabled=yes
